### ISSUE TITLE
✨ Feature Request: Handle auth with amplication

### ISSUE THREAD

**Issue by takanome-dev** [amplication/sample-mobile-app#9]
### What feature would you like to see?

Setup backend with amplication.
For now just handle authentification with [amplication](https://amplication.com/)
Head over to the [docs](https://docs.amplication.com/docs/getting-started/) to get started

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by takanome-dev** [comment]
@yuval-hazaz how should we handle this??

**Comment by yuval-hazaz** [comment]
hi, I am not sure what this feature request is about. can you please explain in more details?

**Comment by takanome-dev** [comment]
I already created the login/signup screens. I  want to setup the backend, create schema for users and handle authentification . I did not try amplication yet  so I have no clue what to do 😅 
Should I go and create an app to start setting up the backend??

**Comment by yuval-hazaz** [comment]
Yes, you can follow this tutorial 
https://docs.amplication.com/docs/tutorials/react-todos/
